### ISSUE TITLE
Which functionality is provided by this library?

### ISSUE THREAD

**Issue by MortInfinite** [FreeApophis/Mumble.net#1]
I was under the impression that this library had functionality for creating a mumble voice connection, but when I looked at the source code I couldn't find any implementation supporting such functionality.

Would you care to elaborate on which functionality this library provides?

**Comment by FreeApophis** [comment]
The library supports the full network stack of the Mumble Protocol, which includes the Audio-Streams in whatever way they are encoded. The audio itself is encoded as CELT and Opus, which can be decoded in whatever way you want. This is not part of the Network-Protocol and and usually Platform dependent.

The AudioPacket class is defined in Coding.cs which is used in ProtocolHandler.cs - the implementation there could probably be improved, but it is enough to transfer audio From and To the Server.

The library does not decode or encode Audio Streams.

This is a library to use for communication with a Mumble-Server it is not a Client Application.

**Comment by MortInfinite** [comment]
Thank you, that was very useful.
